### ISSUE TITLE
Incorrect naming convention

### ISSUE THREAD

**Issue by naiduv** [rickypc/selenium-page-object-generator#1]
It names the variables a little incorrectly.. For instance it names them debianaUsernamePassword1 and debibanaUsernamePassword2, but a correct name would be debianaUsername and debianaPassword.. attached image of html and code in c#.. 

![image](https://cloud.githubusercontent.com/assets/675835/9252937/24fb7200-41a9-11e5-8002-4fc6f966f73d.png)

For some reason
![image](https://cloud.githubusercontent.com/assets/675835/9253003/919ac4ec-41a9-11e5-93c2-28f091c0190e.png)

**Comment by rickypc** [comment]
Venkat,

The reason why the tool did not find the label for the input element is because the "for" attribute do not match with the input element "id" attribute. https://www.w3.org/wiki/HTML/Elements/label#HTML_Attributes

If you are able to change the "for" label attribute to match to "id" input attribute, the tool will give you "password" and "userName" variable names (camel case of label text).

I will take this issue as an enhancement to the tool. Thanks, Venkat.

**Comment by rickypc** [comment]
Version 1.2.2 should return better result without modifying the page source, otherwise please reopen this issue.

**Comment by naiduv** [comment]
Cool!

**Comment by naiduv** [comment]
Sounds good!
